// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: internal/proto/event.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventTriggerService_TriggerEvent_FullMethodName = "/event_trigger.EventTriggerService/TriggerEvent"
)

// EventTriggerServiceClient is the client API for EventTriggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventTriggerServiceClient interface {
	TriggerEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type eventTriggerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventTriggerServiceClient(cc grpc.ClientConnInterface) EventTriggerServiceClient {
	return &eventTriggerServiceClient{cc}
}

func (c *eventTriggerServiceClient) TriggerEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventTriggerService_TriggerEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventTriggerServiceServer is the server API for EventTriggerService service.
// All implementations must embed UnimplementedEventTriggerServiceServer
// for forward compatibility.
type EventTriggerServiceServer interface {
	TriggerEvent(context.Context, *EventRequest) (*EventResponse, error)
	mustEmbedUnimplementedEventTriggerServiceServer()
}

// UnimplementedEventTriggerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventTriggerServiceServer struct{}

func (UnimplementedEventTriggerServiceServer) TriggerEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerEvent not implemented")
}
func (UnimplementedEventTriggerServiceServer) mustEmbedUnimplementedEventTriggerServiceServer() {}
func (UnimplementedEventTriggerServiceServer) testEmbeddedByValue()                             {}

// UnsafeEventTriggerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventTriggerServiceServer will
// result in compilation errors.
type UnsafeEventTriggerServiceServer interface {
	mustEmbedUnimplementedEventTriggerServiceServer()
}

func RegisterEventTriggerServiceServer(s grpc.ServiceRegistrar, srv EventTriggerServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventTriggerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventTriggerService_ServiceDesc, srv)
}

func _EventTriggerService_TriggerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTriggerServiceServer).TriggerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTriggerService_TriggerEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTriggerServiceServer).TriggerEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventTriggerService_ServiceDesc is the grpc.ServiceDesc for EventTriggerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventTriggerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event_trigger.EventTriggerService",
	HandlerType: (*EventTriggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerEvent",
			Handler:    _EventTriggerService_TriggerEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/event.proto",
}
